services: 
  db: # database service
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: speek
      POSTGRES_USER: ${DATABASE_USER} # from env
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
    - '5432:5432'
    env_file:
    - .env
    volumes: # persistent data
    - db_data: /usr/lib/postgresql/16/bin/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s # for now since small db
  makemigrations: # django makemigrations
    container_name: django-makemigrations
    image: django-makemigrations
    env_file:
      - .env
    build: .
    command: python manage.py makemigrations
    volumes: 
      - web_data: .:/app 
    depends_on: 
      db: 
        condition: service_healthy
  migrate: # django migrate
    container_name: django-migrate
    image: django-migrate
    env_file:
      - .env
    build: .
    command: python manage.py migrate
    depends_on:
      makemigrations:
        condition: service_completed_successfully
  server: # webserver
    container_name: webserver
    image: django-server
    env_file:
      - .env
    ports:
      - '8000:8000'
    # later na it gunicorn
    command: python manage.py runserver 0.0.0.0:8000
  volumes: 
    - web_data: .:/app
  depends_on:
    migrate: 
      condition: service_completed_successfully
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
    interval: 5s
    timeout: 3s
    retries: 5
    start_period: 10s
volumes:
  web_data:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /data/db_data
      o: bind


  